### ISSUE TITLE
Requirement Info

### ISSUE THREAD

**Issue by seanrs** [JonasSamuelsson/Handyman#84]
I would like to know what is the version VS you are using, and other info. Interesting to run and test your works. Thank you sir.

**Comment by JonasSamuelsson** [comment]
I'm using Visual Studio Community 16.4
The code is targeting netstandard 2.0, .net 4.7.2, .net core 2.1/3.0/3.1.

**Comment by JonasSamuelsson** [comment]
Is there anything else you are wondering about, otherwise I'll go ahead and close this.
